name: 'main'

on:
  push:
    branches:
      - master
      - task1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Project checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: GTest download
        run: git clone https://github.com/google/googletest.git googletest
      - name: GTest compile and install
        working-directory: ./googletest
        run: |
          sudo cmake .
          sudo cmake --build . --target install
      - name: Project build
        working-directory: ./task1
        run: |
          cmake -B build
          cmake --build build
      - name: Test
        working-directory: ./task1/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: gtests/build_version_tests 
